### ISSUE TITLE
Linked Open Data portal down ?

### ISSUE THREAD

**Issue by Ezekiel-DA** [NYTimes/public_api_specs#10]
Hi,

The Linked Open Data portal at http://data.nytimes.com referenced in the Semantic API documentation appears to be down.
The documentation contains examples like `http://data.nytimes.com/47452218948077706853`, which is not responding, but even the base URL that should supposedly give access to the vocabulary also seems to be down.

Is this by design or will this data return at some point ?

Thanks !

**Comment by nyt-hughmandeville** [comment]
NYT's Linked Data portal was shutdown.  

The Semantic API provides much of the information that the Linked Data portal did.

  http://api.nytimes.com/svc/semantic/v2/concept/search.json?query=Obama&api-key=XXXX
  http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_per/Obama,%20Barack&api-key=XXXX

The Semantic API is currently being overhauled, and unfortunately the documentation is out-of-date.  We are working on fixing that.

  http://developer.nytimes.com/semantic_api.json#/README
