### ISSUE TITLE
Article API Returns Inconsistent Results

### ISSUE THREAD

**Issue by mickzivkovic** [NYTimes/public_api_specs#11]
I'm seeing inconsistent results in the Search API responses.  

For example, the following query, executed twice just a few minutes apart, returns completely different results.

Query:

http://api.nytimes.com/svc/search/v2/articlesearch.json?q=PILLSBURY&sort=oldest&page=3&api-key=xxx

Results 1 and 2 are attached.

Thanks,

Mick

[result2.txt](https://github.com/NYTimes/public_api_specs/files/419530/result2.txt)
[result1.txt](https://github.com/NYTimes/public_api_specs/files/419531/result1.txt)

**Comment by bsvingen** [comment]
It looks like the sorting is different in the two cases - are you able to reproduce this?
