### ISSUE TITLE
Semantic API documentation incomplete

### ISSUE THREAD

**Issue by thinkcontext** [NYTimes/public_api_specs#12]
The docs the Semantic API say there are 4 concept types (geo, per, org, des).  However it appears there are others, I've encountered porg and ttl as well.  Are there any more?  What do they mean?

**Comment by johndaniels** [comment]
Hi there,

I apologize for the documentation being out of date, but hopefully I can answer your question.

This is the full list of types for the semantic API:
- nytd_per (People)
- nytd_geo (Locations)
- nytd_org (Organizations)
- nytd_porg (Public Companies)
- nytd_ttl (Stands for Title, refers to books, movies, etc.)
- nytd_des (General concepts, such as 'crime')
- nytd_topic (A topic that the New York Times writes about, generally involves a specific  guide or topic page on the website)

Hope that helps!

**Comment by nyt-hughmandeville** [comment]
Updated docs.
https://developer.nytimes.com/docs/semantic-api-product/1/overview
