### ISSUE TITLE
Top Stories API Response: Different object types

### ISSUE THREAD

**Issue by leomindez** [NYTimes/public_api_specs#15]
When I am trying to parse the object from Top stories API. There are different types for: 
"org_facet"
"per_facet"
"geo_facet"
"multimedia"

When the fields are empty the type is a string no is an array. It causes and error when I m trying to parse the json object: 

Example: 

**Not empty** 
_"org_facet": ["Islamic State in Iraq and Syria (ISIS)"]_

**Empty** 
_"org_facet":""_

**Comment by RahulSDeshpande** [comment]
Hey @leomindez have you found any solution for this issue ?
If so, can you please share ?

**Comment by leomindez** [comment]
@RahulSDeshpande  Use version 2 of the API.

**Comment by RahulSDeshpande** [comment]
@leomindez Okay thanks for the quick response :)

I tried, but didn't work :(
It seems NYT's v2 API has been deprecated & 'news' API is not working, also I cannot find any documentation or swagger doc for the v2 API :(
Current active API version is v4

Anyways, thanks !!
Let me know if you find anything 👍

Cheers !!
