### ISSUE TITLE
"Replies" field incomplete

### ISSUE THREAD

**Issue by handrew** [NYTimes/public_api_specs#16]
Hi,

I'm trying to get all the comments on a given news article. For any returned comment c, the field "c['replies']" only contains up to 3 actual replies, whereas c['replyCount'] could indicate that there are more. When I double check on the actual web page, there are indeed a c['replyCount'] number of replies.

Is this a feature or a bug?

Thanks!
Andrew

**Comment by MixedMessages** [comment]
Hey @handrew! Could you please provide an example where this is happening for us to look at?

**Comment by handrew** [comment]
http://www.nytimes.com/2015/08/27/us/wdbj7-virginia-journalists-shot-during-live-broadcast.html

You may have to adjust the "offset" number until you get to  it, but the parent comment that starts with "My comments will probably not be published because" has replyCount 5 but only 3 comments in replies. 

Thanks @MixedMessages

**Comment by MixedMessages** [comment]
@handrew 
Seems like it's a feature! We have a limit to the number of replies we return (capped at the latest 3 approved replies). 
`replyCount` is, however, detailing how many replies that comment has received in total. 

Hope that helps!

**Comment by handrew** [comment]
nooooooo :( 

thanks @MixedMessages ! appreciate the response

**Comment by handrew** [comment]
@MixedMessages , another question -- any chance I could get my API rate limit increased? I'm not using it for any commercial purpose

**Comment by scottefein** [comment]
If you email code@nytimes.com we can help you out. Just specify what you're doing and how you're using the data.

**Comment by handrew** [comment]
@scottefein  thanks! I emailed but haven't gotten a response yet.

**Comment by handrew** [comment]
@scottefein , hi, if it helps, the thing is finally live: http://www.overherd.io/
