### ISSUE TITLE
apikey or api-key?

### ISSUE THREAD

**Issue by rogerhu** [NYTimes/public_api_specs#18]
https://github.com/NYTimes/public_api_specs/blob/master/article_search/article_search_v2.json#L22

Also, is the api-key required for the article search API?  It seems to return responses regardless of the API keys, and the rate limits are no different.

**Comment by nyt-hughmandeville** [comment]
It is api-key.  We are working on an issue with api-key checking with the Article Search API.  Currently when the api-key checking doesn't work, it defaults to IP address checking.
