### ISSUE TITLE
limit article search results?

### ISSUE THREAD

**Issue by indefinitelee** [NYTimes/public_api_specs#19]
hi, is there a way to limit the number of articles returned from a query? 
I'd like to return only 10 articles from a given date (for example), or say 20 articles mentioning "Obama" within a data range. 

Sorry if this is documented and I'm just not seeing it. 

Thanks.

**Comment by nyt-hughmandeville** [comment]
Some APIs support query parameters limit and offset.

With the Article Search API, it always returns a max of 10 results.  Use page=N to paginate thru results.

http://api.nytimes.com/svc/search/v2/articlesearch.json?q=obama&begin_date=20160901&end_date=20160930&page=0&api-key=<your-key>

http://api.nytimes.com/svc/search/v2/articlesearch.json?q=obama&begin_date=20160901&end_date=20160930&page=1&api-key=<your-key>
