### ISSUE TITLE
Confused search for article information by url

### ISSUE THREAD

**Issue by newscloud** [NYTimes/public_api_specs#20]
Hi... 

What's the proper query for finding the information for a particular story URL
e.g. article_uri=/2016/11/27/us/politics/trump-adviser-steps-up-searing-attack-on-romney.json

I can't get it to work at all

http://api.nytimes.com/svc/semantic/v2/concept/article/2016/11/27/us/politics/trump-adviser-steps-up-searing-attack-on-romney.json?fields=all&api-key=xxx

**Comment by johndaniels** [comment]
Hi!

The functionality for getting a list of concepts from an has been migrated out of the semantic API, which is mainly used for querying the list of semantic concepts that the New York Times maintains. 

Under the hood, the article lookup for the semantic API was actually querying our article search API, so for example you can get an article and its keywords by querying http://api.nytimes.com/svc/search/v2/articlesearch.json?fq=web_url:%22http://www.nytimes.com/2016/11/27/us/politics/trump-adviser-steps-up-searing-attack-on-romney.html%22&api-key=xxx

You can see the list of Keywords under the 'keywords' property.

If you want to query a particular keyword in the API, you can use the following to query a person by name:
http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_per/Conway,%20Kellyanne?api-key=xxx

Alternatively, replace 'nytd_per' with the appropriate concept type. That said, querying the concept doesn't get you that much more information.

Hope that helps!

**Comment by newscloud** [comment]
Thanks for the fast response. If I just want the web title, is there a simpler way to fetch that? below it only looks like print_headline or keyword main even comes close to this? What's the not going to change variable to use? 

Also was this somewhere in your documentation clearly? I just couldn't figure it out anywhere. And I do a lot of API work.

`{"response":{"meta":{"hits":1,"time":30,"offset":0},"docs":[{"web_url":"http:\/\/www.nytimes.com\/2016\/11\/27\/us\/politics\/trump-adviser-steps-up-searing-attack-on-romney.html","snippet":"The president-elect made the unsubstantiated claim as part of a storm of Twitter posts voicing anger about a three-state recount push....","lead_paragraph":"The president-elect made the unsubstantiated claim as part of a storm of Twitter posts voicing anger about a three-state recount push.","abstract":"Donald Trump makes baseless claim that he would have won popular vote as well as Electoral College were it not for millions of illegal ballots; daylong flurry of Twitter posts by Trump follows announcement by Hillary Clinton's campaign that it will participate in recount effort; outburst also comes amid growing internal rift in transition team over consideration of Mitt Romney for secretary of state.","print_page":"1","blog":[],"source":"The New York Times","multimedia":[{"width":190,"url":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-thumbWide.jpg","height":126,"subtype":"wide","legacy":{"wide":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-thumbWide.jpg","wideheight":"126","widewidth":"190"},"type":"image"},{"width":600,"url":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-articleLarge.jpg","height":422,"subtype":"xlarge","legacy":{"xlargewidth":"600","xlarge":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-articleLarge.jpg","xlargeheight":"422"},"type":"image"},{"width":75,"url":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-thumbStandard.jpg","height":75,"subtype":"thumbnail","legacy":{"thumbnailheight":"75","thumbnail":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-thumbStandard.jpg","thumbnailwidth":"75"},"type":"image"}],"headline":{"main":"Trump Claims, With No Evidence, That \u2018Millions of People\u2019 Voted Illegally","print_headline":"Trump Promotes a Baseless Claim on Illegal Voting"},"keywords":[{"rank":"1","is_major":"Y","name":"persons","value":"Trump, Donald J"},{"rank":"11","is_major":"N","name":"organizations","value":"Twitter"},{"rank":"2","is_major":"Y","name":"subject","value":"Presidential Election of 2016"},{"rank":"3","is_major":"Y","name":"persons","value":"Romney, Mitt"},{"rank":"4","is_major":"N","name":"persons","value":"Conway, Kellyanne"},{"rank":"5","is_major":"N","name":"persons","value":"Priebus, Reince R"},{"rank":"6","is_major":"N","name":"persons","value":"Elias, Marc E"},{"rank":"7","is_major":"N","name":"persons","value":"Clinton, Hillary Rodham"},{"rank":"8","is_major":"N","name":"persons","value":"Stein, Jill"},{"rank":"9","is_major":"N","name":"subject","value":"Voting and Voters"},{"rank":"10","is_major":"N","name":"subject","value":"United States Politics and Government"}],"pub_date":"2016-11-27T16:49:29+0000","document_type":"article","news_desk":"National","section_name":"U.S.","subsection_name":"Politics","byline":{"contributor":"Michael D. Shear reported from Washington, and Maggie Haberman from New York.","person":[{"organization":"","role":"reported","firstname":"Michael","rank":1}],"original":"By MICHAEL D. SHEAR and MAGGIE HABERMAN"},"type_of_material":"News","_id":"583b0e9d95d0e03926072b05","word_count":"1221","slideshow_credits":null}]},"status":"OK","copyright":"Copyright (c) 2013 The New York Times Company.  All Rights `Reserved."}``

**Comment by johndaniels** [comment]
You can specify to only get the headline of an article by using 'fl=headline' as part of your query string.   This is documented at https://developer.nytimes.com/article_search_v2.json#/Documentation/GET/articlesearch.json, although we could do a better job with having examples of returned documents etc. You probably want to use the 'main' headline if you're for the web title.

Otherwise, in the standard response, you'll see that there is a headline object off of the only document that was found, which should be the web headline. 

Unfortunately I picked a bad example to search for because there is another glitch (that we are now looking into) where the URL clearly does not match the headline/body of the article. If you visit that URL you'll see that the headline returned by the API matches the headline displayed at that web page, and the article is clearly _not_ about Romney.

**Comment by newscloud** [comment]
Thanks so much for the great support. I'll give these a try.

**Comment by jasrub** [comment]
While the article search API returns keywords, it does not return taxonomies. Is there any way to query for taxonomies in an article?

**Comment by johndaniels** [comment]
@jasrub I'm not sure if this answers your question, but the keywords for the article are actually unique identifiers in our semantic database system, so to the extent you can look up concepts, you can look up semantic concepts by name in our semantic API.

**Comment by raza08** [comment]
@marzagao @caiogondim @caiogondim @tiffehr @mericson  Could you please let me know how to get image from `"url":"images\/2016\/11\/28\/us\/28TRANSITION2-web\/28TRANSITION2-web-thumbWide.jpg"`becuase it has not valid url to fetch image in article json.

**Comment by nyt-hughmandeville** [comment]
Images are relative paths. Prefix "https://static01.nyt.com/" to the image path to get the full URL.

https://static01.nyt.com/images/2016/11/28/us/28TRANSITION2-web/28TRANSITION2-web-thumbWide.jpg

**Comment by raza08** [comment]
Okay, I got the images with prefix "https://static01.nyt.com/" or "https://www.nytimes.com/", thank you @nyt-hughmandeville .
