### ISSUE TITLE
Article search by category

### ISSUE THREAD

**Issue by trooperandz** [NYTimes/public_api_specs#21]
Hello,

I am having difficulty determining how to conduct an Article search by topic/category.  I would think this would be more straight forward, to provide a 'category' or 'topic' parameter, but I can't seem to find an explanation for this type of search in the documentation.  Any help is greatly appreciated!

Thank you!

**Comment by bkoski** [comment]
Hi Matt,

To search by category, you'll need to use the `fq` parameter described here: http://developer.nytimes.com/article_search_v2.json#/README

There are actually four main types of topics: `organizations`, `persons`, `glocations`, and `subject`.  Using the [Times Tags API](http://developer.nytimes.com/times_tags_v3.json#/README), you can discover the structured terms that you can query on.

It's also possible to use a `.contains` modifier on many of the fields to do a substring match on the terms.  For example:

```
https://api.nytimes.com/svc/search/v2/articlesearch.json?&fq=subject.contains:(%22internet%22)&sort=newest&api-key=....
```

**Comment by nyt-hughmandeville** [comment]
You can search by the semantic tags.

```
  creative_works:"The Joy of Painting (TV Program)"
  persons:"Ross, Bob"
  organizations:"Smithsonian Institution"
  subject:"Immigration and Emigration"
  subject:"Computers and the Internet"
```

articlesearch.json?fq=persons%3A"Ross%2C%20Bob"
