### ISSUE TITLE
Using Semantic API for getting descriptors and taxonomies for an article

### ISSUE THREAD

**Issue by jasrub** [NYTimes/public_api_specs#24]
I'm interested in getting all the taxonomies and descriptors for specific articles.
Trying this request:
http://api.nytimes.com/svc/semantic/v2/concept/article/2010/09/30/energy-environment/30safety.json?fields=all&api-key=xxx 
from the documentation returns the following response:
```
<!DOCTYPE` HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

What would be the right way to query for an article semantic features?

**Comment by JayeetaP** [comment]
Any solution for this issue?

**Comment by nyt-hughmandeville** [comment]
You can get the semantic tags from the Article Search API.  Use web_url filter to get results for one article.  The response has the semantic tags under keywords.

articlesearch.json?fq=web_url%3A"https%3A%2F%2Fwww.nytimes.com%2F2010%2F09%2F30%2Fbusiness%2Fenergy-environment%2F30safety.html"

```
"keywords": [
{
"name": "organizations",
"value": "BP Plc",
"rank": 1,
"major": "N"
},
{
"name": "glocations",
"value": "Gulf of Mexico",
"rank": 2,
"major": "N"
},
{
"name": "subject",
"value": "APPOINTMENTS AND EXECUTIVE CHANGES",
"rank": 3,
"major": "N"
},
...
```
