### ISSUE TITLE
web_url returning incomplete urls?

### ISSUE THREAD

**Issue by nachtm** [NYTimes/public_api_specs#26]
Hi,

You were super-prompt responding to my last question so first of all, thanks!

I'm making a request like the one generated by the api console below:
```// Built by LucyBot. www.lucybot.com
var url = "https://api.nytimes.com/svc/search/v2/articlesearch.json";
url += '?' + $.param({
  'api-key': "232c8759b11f4986bcef2e33a31fb713",
  'fq': "persons:(\"Obama, Barack\")",
  'begin_date': "20090808",
  'end_date': "20090815",
  'page': 4
});
$.ajax({
  url: url,
  method: 'GET',
}).done(function(result) {
  console.log(result);
}).fail(function(err) {
  throw err;
});
```
One of the results returned includes the field `"web_url": "/data/daily/2009/08/11/376388.sgml"` Based on the other fields, it looks like this article is the same as the article at `http://query.nytimes.com/gst/fullpage.html?res=940DE4D9113AF932A2575BC0A96F9C8B63`. Is there a way for me to get the second url (which I can actually get to) given the first? 

Thanks!

**Comment by nyt-hughmandeville** [comment]
Looks like a bug with the search API.  I think the correct URL is

  http://query.nytimes.com/gst/fullpage.html?res=940DE4D9113AF932A2575BC0A96F9C8B63

**Comment by nachtm** [comment]
Yeah that's kinda what I figured. Is there a workaround so that I can get that URL with a similar query? This isn't the only result giving me an oddly-formed URL.

**Comment by nyt-hughmandeville** [comment]
I'm no longer seeing the sgml file path in the web_url field.

```articlesearch.json?fl=web_url&fq=persons%3A"Obama%2C%20Barack"&sort=newest&begin_date=20090810&end_date=20090812&page=0```
