### ISSUE TITLE
Community API

### ISSUE THREAD

**Issue by harishsmenon** [NYTimes/public_api_specs#29]
Hi,
The Community API does not fetch all comments from an article. e.g. in this article, https://www.nytimes.com/2017/01/17/us/politics/betsy-devos-education-senate-hearing.html?_r=0 there are 678 total comments and replies. But only 26 comments are available via API. I have implemented pagination as well. Also, for all comments where repliesCount>0, no replies are fetched.   I have similar issues with other NYTimes articles. Please advice.
Thanks,
Harish

**Comment by nyt-hughmandeville** [comment]
Unfortunately the current Community API is deprecated.  NYT is working on a new Comments API.

  https://www.nytimes.com/2017/06/13/insider/have-a-comment-leave-a-comment.html

**Comment by hsmenon** [comment]
Thank you for the quick response. Truly appreciate it. What is the planned/tentative release date of the new Comments API?
Thanks,
Harish

**Comment by sebastian-adam** [comment]
Hi @nyt-hughmandeville, any updates on the new Comments API? If an ETA isn't available can you at least confirm that this project is still alive and not retired?

**Comment by mreifman** [comment]
We don't have a release date yet but the project is indeed alive.

**Comment by AashitaK** [comment]
Hi @nyt-hughmandeville, any updates on the community API? I have noticed that for certain articles, the API only returns all the comments that were NYT's pick. For example, the article mentioned above as well as this one: [https://www.nytimes.com/2018/04/04/technology/mark-zuckerberg-testify-congress.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=first-column-region&region=top-news&WT.nav=top-news](url)

**Comment by razi-rais** [comment]
@mreifman Any updates? Is there a beta version that is available so folks can at least evaluate it?

**Comment by nyt-hughmandeville** [comment]
Beta version of the Community API is now up on the Developer Portal.

https://developer.nytimes.com/docs/community-api-product/1/overview
