### ISSUE TITLE
Community (recent.json) not returning JSON

### ISSUE THREAD

**Issue by julienmansier** [NYTimes/public_api_specs#3]
I got my new API key and tested (using the API Console) 'Recent Comments' under the Community API, which is used in my app. The response is script and HTML instead of JSON. I have the response posted below:

<!DOCTYPE html>
<html lang="en">
<head>
<title>Help - The New York Times</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="description" content="" />
<meta name="asset_id" content="">
<meta name="CG" content="help">
<meta name="SCG" content="">
<meta name="PT" content="Section Front">
<meta name="PST" content="">
<meta name="viewport" content="width = device-width, user-scalable=0, maximum-scale=1.0, minimum-scale=1.0">
<link rel="alternate" type="application/rss+xml" title="RSS" href=""/>
<meta name="robots" content="noarchive,noindex">

<link rel="stylesheet" type="text/css" href="http://graphics8.nytimes.com/css/0.1/screen/build/sitehelp/styles.css" />
<link rel="stylesheet" type="text/css" href="http://graphics8.nytimes.com/css/0.1/screen/build/sitehelp/responsive/styles.css" media="only screen and (max-width: 616px)" />
<link rel="stylesheet" type="text/css" media="print" href="http://graphics8.nytimes.com/css/0.1/print/styles.css">

<script type="text/javascript" src="http://graphics8.nytimes.com/js/common.js"></script>

<script type="text/javascript" src="http://graphics8.nytimes.com/js/common/screen/DropDown.js"></script>

<script type="text/javascript" src="http://graphics8.nytimes.com/js/util/tooltip.js"></script>

</head>
<body>
<a name="top"></a>

<div id="shell">
<ul id="memberTools">
<NYT_DYNAMIC_IFADS Bar1>

<span class="adx-info hidden" style="display:none !important;" campaign="inyt2016_bar1_digi_may_sale_64XLF">Campaign ID: 283562 | Creative: 2_inyt2016_bar1_digi_may_sale_64XLF -- 413258 | Page: www.nytimes.com/content/help/error.html / Targeted Page: www.nytimes.com | Position: Bar1</span>
<style>
@import url(https://a1.nyt.com/fonts/css/fonts.css);.font-smoothing{-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;}.NYT5Style .masthead-tools #bar1-singlepanel{display: inline; vertical-align: top;}.NYT5Style .masthead-tools{padding: 0}#bar1-singlepanel{border: none; position: relative;}.bar1_hover{opacity: 0;}.sub_small_hide{display: none;}#bar1-singlepanel > a{background-color: #6288A5; border: 1px solid #4D7B9F; border-radius: 3px; color: #fff !important; display: inline-block; font-family: franklin-normal-700, sans-serif; font-style: normal; font-weight: 700; font-size: 1em; padding: 7px 10px 6px; text-transform: uppercase; text-decoration: none;-moz-box-sizing: border-box;line-height: 13px;}#bar1-singlepanel > a:hover{background-color: #326891; border: 1px solid #265E8B; text-decoration: none;}#hovercard{width: 450px; height: 330px; display: none; margin-left: -360px; z-index: 1000000152; border: 0; position: absolute; left: 50%; top: 30px; text-align: left; -moz-box-shadow: 0 0 5px #888; -webkit-box-shadow: 0 0 5px #888; box-shadow: 0 0 5px #888; white-space: normal; background: #e0de7b url('http://graphics8.nytimes.com/adx/images/ADS/41/32/ad.413258/bg-bar1.png') 0 0 no-repeat;}#bar1-headline{position: absolute; top: 76px; left: 31px; font-family: karnak-normal-400, sans-serif; font-style: normal; font-weight: 400; font-size: 25px; line-height: 26px; color: #fff; font-weight: 100; width: 300px; text-align: left;}#bar1-headline span{color: #0ea587;}#bar1-subhead{position: absolute; top: 130px; left: 31px; color: #555556; font-family: franklin-normal-700, sans-serif; font-style: normal; font-weight: 700; font-size: 34px; line-height: 30px; width: 300px; text-align: left;}#bar1-cta{font-family: franklin-normal-700, sans-serif; font-style: normal; font-weight: 700; position: absolute; top: 262px; right: 27px; width: 80px; height: 30px; background: #fff; font-size: 11px; line-height: 13px; padding: 0; text-align: center; text-decoration: none; border-radius: 3px;}#bar1-cta a{display: block; height: 100%; cursor: pointer; color: #000; text-decoration: none; text-transform: uppercase; border: 0px; padding-top: 9px;}#hovercard:after{bottom: 100%; left: 350px; border: solid transparent; content: " "; width: 0; height: 0; position: absolute; pointer-events: none; border-bottom-color: #e0de7b; border-width: 8px; margin: 0;}.NYT5Style #hovercard{top: 18px;}.NYT5Style #hovercard a:hover{background-color: #414042;}/* WEBKIT ONLY RULES */@media screen and (-webkit-min-device-pixel-ratio:0){.NYT5Style #hovercard{top: 28px !important; margin-left: -283px;}.NYT5Style #hovercard:after{left: 273px;}}/* EXCLUDING NYT4 INTERACTIVES */#interactiveABC #bar1-singlepanel{display: none;}
.ad.bar1-ad .user-subscriptions-group {
        display: inline;
    }

.bar1-hidden {
    margin-left: 8px;
}   
</style>
<div id="bar1-nyt5wrapper" class="user-subscriptions-group" data-campaign-name="inyt2016_bar1_digi_may_sale_64XLF">
    <ul class="user-subscriptions-menu">
        <li class="bar1-hidden"><span class="bar1--meter--count">1</span> of 10 articles read</li>
<li id="bar1-singlepanel" class="user-subscriptions-menu user-subscriptions-group bar1_hover">
    <a id="nyt-button-sub" class="" href="http://www.nytimes.com/adx/bin/adx_click.html?type=goto&opzn&page=www.nytimes.com&pos=Bar1&sn2=2fe14a5/d7f7f24f&sn1=538bded0/743577ed&camp=inyt2016_bar1_digi_may_sale_64XLF&ad=2_inyt2016_bar1_digi_may_sale_64XLF&goto=http%3A%2F%2Finternational%2Enytimes%2Ecom%2Fsubscriptions%2Finyt%2Flp8U87X%2Ehtml%3Fadxc%3D283562%26adxa%3D413258%26page%3Dwww.nytimes.com%26pos%3DBar1%26campaignId%3D64XLF" target="_blank" data-content-collection="inyt2016_bar1_digi_may_sale_64XLF" data-content-placement="1">Subscribe Now</a>

        <div id="hovercard" class="font-smoothing" data-campaign-name="inyt2016_bar1_digi_may_sale_64XLF">
            <div id="bar1-body">
                <div id="bar1-headline">The Digital Sale<br><span>Ends Today</span></div>
                <div id="bar1-subhead"><b>One Year. 60% off.<br>Unlimited Access.</b></div>
                <div id="bar1-cta"><a href="http://www.nytimes.com/adx/bin/adx_click.html?type=goto&opzn&page=www.nytimes.com&pos=Bar1&sn2=2fe14a5/d7f7f24f&sn1=538bded0/743577ed&camp=inyt2016_bar1_digi_may_sale_64XLF&ad=2_inyt2016_bar1_digi_may_sale_64XLF&goto=http%3A%2F%2Finternational%2Enytimes%2Ecom%2Fsubscriptions%2Finyt%2Flp8U87X%2Ehtml%3Fadxc%3D283562%26adxa%3D413258%26page%3Dwww.nytimes.com%26pos%3DBar1%26campaignId%3D64XLF" target="_blank">Save now</a></div>
            </div>
        </div>
</li>
</ul></div>

<a id="subscribe_small" href="http://www.nytimes.com/adx/bin/adx_click.html?type=goto&opzn&page=www.nytimes.com&pos=Bar1&sn2=2fe14a5/d7f7f24f&sn1=538bded0/743577ed&camp=inyt2016_bar1_digi_may_sale_64XLF&ad=2_inyt2016_bar1_digi_may_sale_64XLF&goto=http%3A%2F%2Finternational%2Enytimes%2Ecom%2Fsubscriptions%2Finyt%2Flp8U87X%2Ehtml%3Fadxc%3D283562%26adxa%3D413258%26page%3Dwww.nytimes.com%26pos%3DBar1%26campaignId%3D64XLF" class="subscribe-link sub_small_hide" data-content-collection="inyt2016_bar1_digi_may_sale_64XLF" data-content-placement="1" target="_blank">Subscribe</a>
<script src="http://graphics8.nytimes.com/marketing/ADX/bar1/bar1_meter_count_v2.js"></script>
</NYT_DYNAMIC_IFADS>

<li><a href="http://www.nytimes.com/membercenter/sitehelp.html">Help</a></li>
</ul>
<div class="mainTabsContainer tabsContainer">
<ul id="mainTabs" class="mainTabs tabs">
<li class="first mainTabHome"><a href="http://www.nytimes.com">Home Page</a></li>
<li class="mainTabTodaysPaper"><a href="http://www.nytimes.com/pages/todayspaper/index.html">Today's Paper</a></li>
<li class="mainTabVideo"><a href="http://www.nytimes.com/video">Video</a></li>
<li class="mainTabMostPopular"><a href="http://www.nytimes.com/mostpopular">Most Popular</a></li>
</ul>
</div>

<div id="page" class="tabContent active">
<div id="masthead" class="wrap">
<NYT_DYNAMIC_IFADS Middle1C>
<div class="singleAd" id="Middle1C">

</div>

</NYT_DYNAMIC_IFADS>

<div id="searchWidget">
<div class="inlineSearchControl">
<form enctype="application/x-www-form-urlencoded" action="http://query.nytimes.com/search/sitesearch" method="get" name="searchForm" id="searchForm">
<input type="hidden" value="full" name="date_select"/>
<label for="searchQuery">Search All NYTimes.com</label>
<input type="text" class="text" value="" size="" name="query" id="searchQuery"/>
<input type="hidden" id="searchAll" name="type" value="nyt"/>
<input id="searchSubmit" title="Search" width="22" height="19" alt="Search" type="image" src="http://graphics8.nytimes.com/images/global/buttons/go.gif" >
</form>
</div>

</div>
<NYT_GLOBAL_EDITION_BRANDING_SF>

<div id="branding"  itemscope itemtype="http://schema.org/Organization">
<a href="http://www.nytimes.com" itemprop="url"><img src="http://graphics8.nytimes.com/images/misc/nytlogo152x23.gif" alt="New York Times" id="NYTLogo" itemprop="logo" /></a>
</div>

</NYT_GLOBAL_EDITION_BRANDING_SF>

<div id="date">
<p>
<NYT_DISPLAYDATE></NYT_DISPLAYDATE>
</p>
</div>

<NYT_GLOBAL_EDITION_LOGO_SF>

<h1>
<a href="http://www.nytimes.com/content/help/error.html">Help</a>        
</h1>

</NYT_GLOBAL_EDITION_LOGO_SF>
</div>

<div id="main">
<div class="spanAB wrap">
<div class="abColumn">
<div id="spanABTopRegion">
<div class="columnGroup first">
<div class="header">
<h2>We're Sorry</h2>
<p> </p>
<p>An error has occurred. Please try again later or <a href="https://myaccount.nytimes.com/membercenter/help.html">contact Customer Service</a> for assistance.</p> 
</div>

</div>
</div>

<div id="SpanABMiddleRegion" class="opening module">
<div id="categoryPages">
</div>  
<div id="faqQuestions">
</div> 
</div>
</div>
<div class="cColumn">
                    <div class="columnGroup first">
<div id="sitehelpSearch" class="box blue">
<div class="insetH insetV">
<div id="yourSearch">
<form enctype="application/x-www-form-urlencoded" name="mainFormTop" method="get" action="http://query.nytimes.com/search/faq">
<label for="yourSearch_query">Search Help</label>
<input type="text" id="yourSearch_query" name="query" class="searchTextbox" size="42">
<input align="absmiddle" class="searchSubmit" value="sub" border="0" name="submit" type="image" src="http://graphics8.nytimes.com/images/global/buttons/go.gif" >
</form>
</div>

</div>
</div>  
</div>
                    <div class="columnGroup ">

<div id="relatedLinks">
</div>

</div>
                    <div class="columnGroup last">
<NYT_DYNAMIC_IFADS Box1>

<div class="bigAd" id="Box1">

</div>

</NYT_DYNAMIC_IFADS>
</div>
</div>
</div>
</div>
<footer class="pageFooter">

<div class="inset">
<nav class="pageFooterNav">
<ul class="pageFooterNavList wrap">
<li class="firstItem"><a href="http://www.nytimes.com/content/help/rights/copyright/copyright-notice.html">&copy; 2016 The New York Times Company</a></li>
<li><a href="http://spiderbites.nytimes.com/">Site Map</a></li>
<li><a href="http://www.nytimes.com/privacy">Privacy</a></li>
<li><a href="http://www.nytimes.com/ref/membercenter/help/privacy.html#pp">Your Ad Choices</a></li>
<li><a href="http://www.nytimes.whsites.net/mediakit/">Advertise</a></li>
<li><a href="http://www.nytimes.com/content/help/rights/sale/terms-of-sale.html ">Terms of Sale</a></li>
<li><a href="http://www.nytimes.com/ref/membercenter/help/agree.html">Terms of Service</a></li>
<li><a href="http://www.nytco.com/careers">Work With Us</a></li>
<li><a href="http://www.nytimes.com/rss">RSS</a></li>
<li><a href="http://www.nytimes.com/membercenter/sitehelp.html">Help</a></li>
<li><a href="http://www.nytimes.com/ref/membercenter/help/infoservdirectory.html">Contact Us</a></li>
<li class="lastItem"><a href="https://myaccount.nytimes.com/membercenter/feedback.html">Site Feedback</a></li>
</ul>
</nav>
</div>
</footer>
</div>
</div>
<script language="JavaScript" type="text/javascript">
                NYTD.require('http://graphics8.nytimes.com/js/app/sitehelp/toggleDialogBoxes.js');
            </script>   
<script type="text/javascript" language="JavaScript">
    NYTD.siteHelp.toggleDialogBoxes();
    </script>
<NYT_DYNAMIC_IFADS Bottom7>

</NYT_DYNAMIC_IFADS>
<NYT_DYNAMIC_IFADS Bottom8>

</NYT_DYNAMIC_IFADS>
<NYT_DYNAMIC_IFADS Bottom9>

</NYT_DYNAMIC_IFADS>
<NYT_DYNAMIC_IFADS Inv1>

</NYT_DYNAMIC_IFADS>
<NYT_DYNAMIC_IFADS Inv2>

</NYT_DYNAMIC_IFADS>
<NYT_DYNAMIC_IFADS Inv3>

</NYT_DYNAMIC_IFADS>
<NYT_DYNAMIC_IFADS ADX_CLIENTSIDE>
<IMG CLASS="hidden" SRC="/adx/bin/clientside/c1e4660bQ2F@@@@@@Q2B@Q2BAQ5BQ3BAsQ2B@o@@@@@@@@Q2BarQ5BjXrIo@@@@@ra)ojr" height="1" width="3">
</NYT_DYNAMIC_IFADS>

            
        
        <img height="1" width="3" border=0 src="http://up.nytimes.com/?d=0//&t=6&s=0&ui=&r=http%3a%2f%2fwww%2enytimes%2ecom%2fref%2fmembercenter%2fapperror%2ehtml&u=www%2enytimes%2ecom%2fcontent%2fhelp%2ferror%2ehtml%3f">
        
    
        
        <script language="JavaScript"></script>
        <script src="http://graphics8.nytimes.com/js/app/analytics/trackingTags_v1.1.js" type="text/javascript"></script>
        <noscript>
          <div><img alt="DCSIMG" id="DCSIMG" width="1" height="1" src="http://wt.o.nytimes.com/dcsym57yw10000s1s8g0boozt_9t1x/njs.gif?dcsuri=/nojavascript&amp;WT.js=No&amp;WT.tv=1.0.7"/></div>

```
    </noscript>
```

</body>
</html>

**Comment by scottefein** [comment]
Hi Julien,

Working on a fix for this. Thanks for letting us know!

**Comment by scottefein** [comment]
This should be fixed now.  Let us know if you run into any problems.

**Comment by julienmansier** [comment]
I reran in the console and I either get [no content] or HTML response 404 - Not Found.

Thanks,
Julien

**Comment by scottefein** [comment]
You need to give it parameters for the console to work.

**Comment by julienmansier** [comment]
The details under /user-content/recent.json has no parameters. 

Thanks,
Julien

**Comment by scottefein** [comment]
Ah. http://api.nytimes.com/svc/community/v3/user-content/recent.json -- that call works. Seems there might be an issue with the console for that one.
