### ISSUE TITLE
HTTP 500 error, specific term on specific dates.

### ISSUE THREAD

**Issue by hypathia** [NYTimes/public_api_specs#32]
Querying 'flu' in the Article Search API over some specific dates (for example, 2009/09/16 or 2009/08/15) leads invariably to a 500 HTTP error:

> {
  "timestamp": 1502585460212,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.core.convert.ConversionFailedException",
  "message": "Failed to convert from type [java.lang.String] to type [java.net.URL] for value '/data/daily/2009/09/16/147800.sgml'; nested exception is java.net.MalformedURLException: no protocol: /data/daily/2009/09/16/147800.sgml",
  "path": "/svc/add/v1/articlesearch.json"
}

**Comment by MaxBittker** [comment]
I've also been getting weird 500 results from this endpoint, specific to certain search terms (with no other parameters!) I suspect they are trying to return weirdly formed documents?


```
var url = "https://api.nytimes.com/svc/search/v2/articlesearch.json";
 {
  'api-key': "xxxxxxxx",
  'q': "dada"
});

```
yields
```
{
  "timestamp": 1513345419766,
  "status": 500,
  "error": "Internal Server Error",
  "message": "Failed to convert from type [java.lang.String] to type [boolean] for value 'y'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value 'y'",
  "path": "/svc/add/v1/articlesearch.json"
}
```

**Comment by nyt-hughmandeville** [comment]
I think this is fixed.

articlesearch.json?q=flu&sort=newest&begin_date=20090915&end_date=20090917&page=0
articlesearch.json?q=flu&sort=newest&begin_date=20090915&end_date=20090917&page=1

**Comment by MaxBittker** [comment]
awesome! what was the problem, i’m curious?
