### ISSUE TITLE
[Movie Review API] publication-date params don't work

### ISSUE THREAD

**Issue by darth-cheney** [NYTimes/public_api_specs#33]
It seems that the params for `publication-date` in the Movies API `/search.json` route are completely ineffective, even in the online Swagger tester.
  
Example:
`https://api.nytimes.com/svc/movies/v2/reviews/search.json?&publication-date=2001-01-01;2001-01-31&api-key=<SOME_KEY>`
  
For me, this always returns the most recent reviews, no matter what date ranges I include.

**Comment by nyt-hughmandeville** [comment]
This is a bug, we have opened an internal ticket.  For now you can try filtering by opening-date which is generally close to the review publication date.

**Comment by dippedrusk** [comment]
It still doesn't work - is this likely to be fixed any time soon?

**Comment by nyt-hughmandeville** [comment]
This is fixed.
