### ISSUE TITLE
Facets not working in articlesearch

### ISSUE THREAD

**Issue by blaschke** [NYTimes/public_api_specs#34]
Calls to the API including `facet_field` and `facet_filter` doenot return facets in the JSON response:

`https://api.nytimes.com/svc/search/v2/articlesearch.json?q=Apple&begin_date=20170801&end_date=20170830&facet_field=source&facet_filter=true&api-key=<SOME_KEY>
`
 
The same is true for the online console: 

`http://developer.nytimes.com/article_search_v2.json#/Console`

**Comment by sckott** [comment]
Same here

**Comment by JoshuaDull** [comment]
I am also having this problem. 
Even the example URL below from the documentation does not return facets!! (http://api.nytimes.com/svc/search/v2/articlesearch.json?fq=romney&facet_field=day_of_week&begin_date=20120101&end_date=20120101&api-key=####
)

**Comment by nyt-hughmandeville** [comment]
Set facet=1 and facet_fields.

http://api.nytimes.com/svc/search/v2/articlesearch.json?fq=romney&facet_fields=day_of_week&begin_date=20120101&end_date=20120101&facet=1&api-key=####

**Comment by sckott** [comment]
thx @nyt-hughmandeville - can that be documented as well?

**Comment by nyt-hughmandeville** [comment]
Docs have info about facets now.
https://developer.nytimes.com/docs/articlesearch-product/1/overview
