### ISSUE TITLE
Just to confirm: no full text of articles via article search route?

### ISSUE THREAD

**Issue by sckott** [NYTimes/public_api_specs#36]
I assume not, but thought I'd ask to make sure. Appears it's only parts of articles, and snippets matching search terms, etc.

**Comment by nyt-hughmandeville** [comment]
Correct, NYT public APIs only return article metadata (url, headline, byline, summary, ...).  They do not return full article body content.

Full article body content from 1987-2007 is available from UPenn for non-commercial use.

  https://catalog.ldc.upenn.edu/ldc2008t19

For commercial use, full article content can be purchased from the NYT Syndication site.

  https://www.nytsyn.com/

**Comment by sckott** [comment]
thx much
