### ISSUE TITLE
TimesTags API broken?

### ISSUE THREAD

**Issue by rbren** [NYTimes/public_api_specs#37]
The [API console](http://developer.nytimes.com/times_tags_v3.json#/Console/GET/timestags.json) seems to be having trouble at least.

**Comment by nyt-hughmandeville** [comment]
The request works with out .json in the URL.

**Comment by nyt-hughmandeville** [comment]
The Times Tags API docs have moved.

https://developer.nytimes.com/docs/timestags-product/1/overview
