### ISSUE TITLE
Score attribute

### ISSUE THREAD

**Issue by elinw** [NYTimes/public_api_specs#40]
When I use article search it returns "score" and sometimes I get two records that are identical except for differing "score" values.  Is this expected behavior or unexpected? I don't see score mentioned in any of the documents. (I'm assuming it's a relevancy score of some kind.)

**Comment by nyt-hughmandeville** [comment]
NYT's Article Search uses Elastic Search which is based on Lucene.  The score is from Elastic Search.

https://www.elastic.co/guide/en/elasticsearch/guide/current/practical-scoring-function.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/scoring-theory.html
