### ISSUE TITLE
article search api does not seem to work, when I try querying

### ISSUE THREAD

**Issue by shegde4** [NYTimes/public_api_specs#41]
The query is as below:-from nytimesarticle import articleAPI
api = articleAPI('4f716a9a9d8f455e908ec32b459a12ac')
articles = api.search(q="Obama", 
                          fq={"headline": "Obama", 
                              "source": ["Reuters", 
                                         "AP", 
                                         "The New York Times"]}, 
                          begin_date="20161001", # this can also be an int
                          facet_field=["source", "day_of_week"], 
                          facet_filter=True)
////////////////////////////////////////////////////////////////////////////////////////
I get the following error:-

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-87b3e0599a04> in <module>()
      8                           begin_date="20161001", # this can also be an int
      9                           facet_field=["source", "day_of_week"],
---> 10                           facet_filter=True)

Z:\Anaconda\lib\site-packages\nytimesarticle.py in search(self, response_format, key, **kwargs)
    109 
    110         url = '%s%s?%sapi-key=%s' % (
--> 111             API_ROOT, response_format, self._options(**kwargs), key
    112         )
    113 

Z:\Anaconda\lib\site-packages\nytimesarticle.py in _options(self, **kwargs)
     82         for k, v in kwargs.items():
     83             if k is 'fq' and isinstance(v, dict):
---> 84                 v = _format_fq(v)
     85             elif isinstance(v, list):
     86                 v = ','.join(v)

Z:\Anaconda\lib\site-packages\nytimesarticle.py in _format_fq(d)
     67                     d[k] = ' '.join(map(lambda x: '"' + x + '"', v))
     68                 else:
---> 69                     d[k] = '"' + v + '"'
     70             values = []
     71             for k,v in d.items():

TypeError: must be str, not bytes

can you please help me figure out if I am going wrong or if the API is broken ?

**Comment by nyt-hughmandeville** [comment]
Try removing square brackets with the source filter.

  "source":"The New York Times"

Looks like source filter with square brackets is causing a shard failure at the moment.

**Comment by shegde4** [comment]
articles = api.search(q="Obama", fq={"headline": "Obama","source": "The New York Times"}, begin_date=20161001)

changed it to the above code removed the square brackets completely as you can see. Throws the same typeerror

**Comment by nyt-hughmandeville** [comment]
There is a shard issue causing problems.  Until that is fixed, you might be able to find some working queries.

q=obama&fq=source%3A"The%20New%20York%20Times"%20AND%20headline%3A"Obama"&begin_date=20161001

**Comment by nyt-hughmandeville** [comment]
Our search team says square bracket syntax is for range queries.  You can achieve the results you want with parentheses if you'd like the disjunction of multiple values for a field, i.e., you can do field:(A B) to mean field:A or field:B.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
