### ISSUE TITLE
APi works wrong with encoded form ("%2B")  for "+" character.

### ISSUE THREAD

**Issue by asadaiev** [NYTimes/public_api_specs#44]
**Steps to reproduce:**
1. Perform GET request to http://api.nytimes.com/svc/mostpopular/v2/mostemailed/Smarter%2BLiving/30.json
2. Check response

**Expected result:** correct answer as we received with:
http://api.nytimes.com/svc/mostpopular/v2/mostemailed/Smarter%20Living/30.json
http://api.nytimes.com/svc/mostpopular/v2/mostemailed/Smarter Living/30.json
http://api.nytimes.com/svc/mostpopular/v2/mostemailed/Smarter+Living/30.json

**Actual result:** 
{
    "status": "OK",
    "copyright": "Copyright (c) 2018 The New York Times Company.  All Rights Reserved.",
    "num_results": 0,
    "results": []
}

**Comment by nyt-hughmandeville** [comment]
Use %20 or + to encode space in the URL.

  http://api.nytimes.com/svc/mostpopular/v2/mostemailed/Smarter%20Living/30.json?api-key=yourkey
