### ISSUE TITLE
All months in 1964 Archive API returning null for all `print_page` values

### ISSUE THREAD

**Issue by russellsamora** [NYTimes/public_api_specs#48]

**Comment by nyt-hughmandeville** [comment]
Thanks for the info.  I verified and I don't see print_page in results for 1964 either.  I have opened an internal ticket with our Search team.

**Comment by russellsamora** [comment]
Great, this is also true of Sep and Oct 1978.

**Comment by nyt-hughmandeville** [comment]
There were no NYT articles published in 9/1978 and 10/1978.

From Wikipedia: “August 10, 1978, to November 5, 1978. A multi-union strike shut down the three major New York City newspapers. No editions of The New York Times were printed.”
