### ISSUE TITLE
Several API spec discrepancies

### ISSUE THREAD

**Issue by leslie-heinzen** [NYTimes/public_api_specs#49]
Hello,

Thanks for making these API specs publicly available. 

I have found several discrepancies between the API specs available in this repo and those served from the developer portal. For example, comparing the article search api spec here and a parsed snapshot of the one served from the developer portal:

* https://raw.githubusercontent.com/NYTimes/public_api_specs/master/article_search/article_search_v2.json

* https://developer.nytimes.com/portals/api/sites/nyt-devportal/liveportal/apis/articlesearch-product/spec

There are many diffs -- the one in this repo appears to be v1. Can I assume that the specs served from the developer portal are the source of truth? Cursory testing seems to indicate this. If this is the case I would be happy to make some PRs to update the specs here.

Thanks for your time.

**Comment by nyt-hughmandeville** [comment]
The specs in the developer portal are updated versions of those in the public_api_specs repo.  

I checked in the dev portal versions into public_api_specs.  They are YAML files instead of JSON files (e.g. article_search_v2.yaml).  We'll remove the old JSON versions.
Thanks
