### ISSUE TITLE
Section ID List

### ISSUE THREAD

**Issue by Stengo** [NYTimes/public_api_specs#5]
First of all, thank you for the open API. It has been really nice to use real data in my first internship project.

However, I did notice a problem with your section identification for the Most Popular API. The "sections-list" call returns section names, but no IDs.

Initially I thought those were easily convertible to their respective IDs, but that is not the case. For example, "Business Day" is associated with the section ID "business" and in some cases, like "U.S.", it seems impossible to find the corresponding ID (e.g. U.S./US/us/... do not work).

Is there a way to find all available IDs, possibly even included in the "sections-list" call?

**Comment by nyt-hughmandeville** [comment]
Can you provide the URLs you are having trouble with?
Filtering by section is working for me.

  /svc/mostpopular/v2/mostemailed/Business%20Day/1.json
  /svc/mostpopular/v2/mostemailed/U.S./1.json

**Comment by Stengo** [comment]
Interesting, I relied on the default json response and used

/svc/mostpopular/v2/mostemailed/Business%20Day/1
/svc/mostpopular/v2/mostemailed/U.S./1

While business works like that, U.S. does not. But making json explicit solves the problem for me.
Thank you!
