### ISSUE TITLE
Article serach API how to get URL for image for each article

### ISSUE THREAD

**Issue by ajoytech** [NYTimes/public_api_specs#52]
How to get Url for image source of each article in Article search API
https://api.nytimes.com/svc/search/v2/articlesearch.json?api-key=<key>&q=sometext&page=0

In this API hit it returns a "multimedia" [object]  which contain attribute -->
"url": "images/2016/12/14/us/14zinke/00zinke-thumbStandard.jpg"

I tried to append this url with base url and web_url as well, not able to get the image.
Just wondering how can I download image for each article here?

**Comment by nyt-hughmandeville** [comment]
You can prefix the image path with static01.nyt.com or www.nytimes.com to get the full URL of the image.

http://static01.nyt.com/images/2016/12/14/us/14zinke/00zinke-thumbStandard.jpg
http://www.nytimes.com/images/2016/12/14/us/14zinke/00zinke-thumbStandard.jpg

**Comment by Derickoh** [comment]
Thanks, really helpful
