### ISSUE TITLE
Stale content on topstories.

### ISSUE THREAD

**Issue by j-e-d** [NYTimes/public_api_specs#54]
It looks like https://api.nytimes.com/svc/topstories/v2/home.json is returning old content. The most recent article there is two days old (2020/01/08). Did you change the way to use the API?
The site https://developer.nytimes.com is down so I can't check if changes not documented here where added.

Thanks.

**Comment by nyt-hughmandeville** [comment]
Thanks for reporting the issue.  We are working on a fix, it could take a few days.
In the meantime, you can use the RSS feeds to get the latest articles on the home page (and other sections).  No API key is required.

  * https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

There are docs for the RSS feed on the developer portal.  

  * https://developer.nytimes.com/docs/rss-api/1/overview

**Comment by j-e-d** [comment]
When I try to access the developer portal I receive a web page with the following message:

"The site you requested doesn't exist."

**Comment by nyt-hughmandeville** [comment]
Can you send a screenshot and what developer.nytimes.com resolves to on your machine (using dig or nslookup)?  I also emailed you, if that is easier.

```  
  $ dig developer.nytimes.com
  developer.nytimes.com. 288 IN CNAME nyt-portal.apigee.net.
  nyt-portal.apigee.net. 88 IN CNAME agea1rt001-0-routers.dn.apigee.net.
  agea1rt001-0-routers.dn.apigee.net. 60 IN A 35.227.123.243
```

**Comment by j-e-d** [comment]
Sorry, it's working. Looks like I had some local issues. When I entered a private window with no adblockers it showed the correct page.

**Comment by nyt-hughmandeville** [comment]
Top Stories API should have current data again now.

 * https://api.nytimes.com/svc/topstories/v2/home.json?api-key=yourkey
